# Generated by Django 3.2.8 on 2021-10-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'default_related_name': 'meals'},
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='food',
            new_name='meal',
        ),
    ]
